### PR TITLE
Create JSON-LD 1.1 Framing as a third normative deliverable.

### PR DESCRIPTION
**Pull request by gkellogg**

### CODE REVIEW

**Review by dlongley — APPROVED** [review]

**Review by azaroth42 — APPROVED** [review]
:+1: from me.  How many reviews per change do we expect before merging?

**Comment by iherman** [comment]
I was late to the party for commenting... I do have one (non critical) comment: The charter makes the decision for the Frame API to be a separate document. Is there a reason why this could not be part of the API document (as was in the previous version of the charter)?

In many respect, it is easier for a WG to decide that a specific technology deserves two documents and not one, ie, split a listed deliverable into two documents. I am a little bit worried that it is slightly more difficult to explain whey two deliverables would be merged into one document. In this sense, the previous version had more flexibility in it.

However, I was not part of the discussions leading to this change, so if you guys think there are very good argument (e.g., readability) that dictates to have three documents instead of two once and for all, I am fine.

**Comment by gkellogg** [comment]
You can see the CG discussion here: https://json-ld.org/minutes/2018-02-05/#topic-8. The groups feeling was that it both caused the spec to bloat, and that it might. It be universally adopted, making implementations not be able to pass 100% of the API tests. Better to leave it as a separate document.

Gregg Kellogg

**Comment by iherman** [comment]
Thanks @gkellogg. If there is a slightest chance that there won't be enough implementations for Framing to pass the CR phase then I agree with the choice. That seems to be the case...

**Comment by gkellogg** [comment]
There are already 2 conforming implementations, it’s more a matter of managing implementation profiles, and keeping the doc separate allows otherwise conforming implementations to claim full compatibility. The “framing profile” then becomes an additional layer that some may strive for. I could imagine separating out other subsets, but not necessarily by splitting them from the document. Expansion, RDF serialization and deserialization, compaction and flattening are reasonably separate concerns. So might be a streaming profile.

**Pull request merged**
