### PR TITLE
First attempt for a set of changes answering the comments of FactMission

### PR DESCRIPTION
**Pull request by iherman**

### CODE REVIEW

**Comment by iherman** [comment]
Guys, this is a first attempt to answer to the latest issues on the charter. There is also a rawgit version:

    https://rawgit.com/json-ld/charter/FactsMission-comments/index.html

Any comments? 

/cc @azaroth42 @gkellogg @BigBlueHat

**Review by BigBlueHat — APPROVED** [review]
Looks great, Ivan. No complaints.

**Comment by azaroth42** [comment]
Yup, LGTM :)

**Review by azaroth42 — APPROVED** [review]

**Review by gkellogg — APPROVED** [review]

**Comment by davidlehn** [comment]
"Detailed comparisons with other RDF serialization formats will also be included."

What is the purpose of putting this comparison in the spec itself?  This sort of survey seems like a very useful living document to have in general, but perhaps it should be in a common RDF location and updated as JSON-LD and other specs evolve or are created.  Hard coding a contemporary comparison in a specific version of one of the serialization specs seems odd and could be misleading for future readers.

**Comment by iherman** [comment]
@davidlehn you are right to question that (although this is the way it is JSON-LD 1.0 already). But this is not a decision we have to take now. Here is what I propose: there was already a sentence in the document:

> Note that the WG may decide, based on editorial and readability considerations, to spin off the HTTP protocol related sections into a separate Recommendation.

I have added the sentence:

> The comparison sections on RDF serializations may also be published as a separate Working Group Note rather than (non-normative) sections of the respective Recommendation.

Is it o.k.?

**Comment by davidlehn** [comment]
Seems I forgot we had that section in the spec already!  Not sure what should be done with that but the charter language now gives some flexibility.  Looks ok to me.  Thanks.

**Comment by iherman** [comment]
The change proposals have been accepted by the commenter; merging and closing.

**Pull request merged**
